version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: rid_mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rid_web_db_new
      MYSQL_USER: rid_user
      MYSQL_PASSWORD: rid_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: